/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package solucion3;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtmetroscuadrados = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtcuotainicial = new javax.swing.JTextField();
        txtmontodecuota = new javax.swing.JTextField();
        cmdcalcular = new javax.swing.JButton();
        cmdborrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("INMOBILIARIA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 120, -1));

        jLabel2.setText("Número de metros cuadrados");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 150, -1));

        jLabel3.setText("Cuota Inicial");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        txtmetroscuadrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmetroscuadradosActionPerformed(evt);
            }
        });
        txtmetroscuadrados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmetroscuadradosKeyTyped(evt);
            }
        });
        getContentPane().add(txtmetroscuadrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 80, -1));

        jLabel4.setText("Monto de cuotas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        txtcuotainicial.setEditable(false);
        getContentPane().add(txtcuotainicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 100, -1));

        txtmontodecuota.setEditable(false);
        getContentPane().add(txtmontodecuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 110, -1));

        cmdcalcular.setText("CALCULAR");
        cmdcalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdcalcularActionPerformed(evt);
            }
        });
        getContentPane().add(cmdcalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        cmdborrar.setText("BORRAR");
        getContentPane().add(cmdborrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdcalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdcalcularActionPerformed
   double mt,mp,nmc,mi,mc;
   String res1,res2;
   
     if(txtmetroscuadrados.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this,"Digite la cantidad invertida por inversionista  tres","Error", JOptionPane.ERROR_MESSAGE);
         txtmetroscuadrados.requestFocusInWindow();
     }else{
   
   nmc=Double.parseDouble(txtmetroscuadrados.getText());
   
   
   mt=nmc*80000;
   mi=mt*0.35;
   mc=(mt-mi)/12;
   
     res1 = String.valueOf(mi);
     txtcuotainicial.setText(res1);
     res2 = String.valueOf(mc);
     txtmontodecuota.setText(res2);
    }//GEN-LAST:event_cmdcalcularActionPerformed
    }
    private void txtmetroscuadradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmetroscuadradosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmetroscuadradosActionPerformed

    private void txtmetroscuadradosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmetroscuadradosKeyTyped
     char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              
              evt.consume(); 
                      
          } 
    }//GEN-LAST:event_txtmetroscuadradosKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdborrar;
    private javax.swing.JButton cmdcalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtcuotainicial;
    private javax.swing.JTextField txtmetroscuadrados;
    private javax.swing.JTextField txtmontodecuota;
    // End of variables declaration//GEN-END:variables
}
